class DataCautionService:

    """
    AlphaForge Data Caution Service

    Converts detailed data-quality and completeness
    information into a simple, visible status:

    CLEAN
        Data is sufficiently complete and no important
        data warnings are present.

    CAUTION
        Enough evidence exists for ranking, but some
        limitations or missing information should remain
        visible to the user.

    INSUFFICIENT
        There is not enough evidence to safely include
        the stock in the normal ranking process.

    IMPORTANT:
    This service does not change fundamental,
    technical, composite, or readiness scores.
    """

    CLEAN = "CLEAN"
    CAUTION = "CAUTION"
    INSUFFICIENT = "INSUFFICIENT"

    # --------------------------------------------------
    # MAIN EVALUATION
    # --------------------------------------------------

    def evaluate(
        self,
        data_quality=None,
        completeness=None,
    ):

        data_quality = (
            data_quality
            if isinstance(
                data_quality,
                dict,
            )
            else {}
        )

        completeness = (
            completeness
            if isinstance(
                completeness,
                dict,
            )
            else {}
        )

        # --------------------------------------------------
        # READ INPUTS
        # --------------------------------------------------

        raw_confidence = (
            data_quality.get(
                "confidence_score"
            )
        )

        coverage_score = (
            completeness.get(
                "coverage_score"
            )
        )

        coverage_level = (
            completeness.get(
                "coverage_level"
            )
        )

        ranking_data_ready = bool(
            completeness.get(
                "ranking_data_ready",
                False,
            )
        )

        blocking_reasons = list(
            completeness.get(
                "blocking_reasons",
                [],
            )
            or []
        )

        completeness_warnings = list(
            completeness.get(
                "warnings",
                [],
            )
            or []
        )

        # --------------------------------------------------
        # INSUFFICIENT
        #
        # If the completeness resolver says there is not
        # enough independent evidence, the stock receives
        # INSUFFICIENT regardless of its numerical score.
        # --------------------------------------------------

        if not ranking_data_ready:

            reasons = list(
                blocking_reasons
            )

            if not reasons:

                reasons.append(
                    "Insufficient data for reliable ranking"
                )

            return {
                "data_status":
                    self.INSUFFICIENT,

                "data_caution":
                    True,

                "raw_confidence":
                    raw_confidence,

                "coverage_score":
                    coverage_score,

                "coverage_level":
                    coverage_level,

                "reasons":
                    reasons,
            }

        # --------------------------------------------------
        # CAUTION DETECTION
        # --------------------------------------------------

        caution_reasons = []

        # Preserve warnings generated by the
        # completeness resolver.

        caution_reasons.extend(
            completeness_warnings
        )

        # Reduced raw-source confidence.

        if (
            raw_confidence is not None
            and raw_confidence < 75
        ):

            caution_reasons.append(
                "Reduced raw-source data confidence"
            )

        # Moderate evidence coverage is rankable,
        # but should remain visibly marked.

        if (
            coverage_score is not None
            and coverage_score < 75
        ):

            caution_reasons.append(
                "Moderate data coverage"
            )

        # Remove duplicate messages while
        # preserving their original order.

        caution_reasons = list(
            dict.fromkeys(
                caution_reasons
            )
        )

        # --------------------------------------------------
        # CAUTION
        # --------------------------------------------------

        if caution_reasons:

            return {
                "data_status":
                    self.CAUTION,

                "data_caution":
                    True,

                "raw_confidence":
                    raw_confidence,

                "coverage_score":
                    coverage_score,

                "coverage_level":
                    coverage_level,

                "reasons":
                    caution_reasons,
            }

        # --------------------------------------------------
        # CLEAN
        # --------------------------------------------------

        return {
            "data_status":
                self.CLEAN,

            "data_caution":
                False,

            "raw_confidence":
                raw_confidence,

            "coverage_score":
                coverage_score,

            "coverage_level":
                coverage_level,

            "reasons":
                [],
        }


def evaluate_data_caution(
    data_quality=None,
    completeness=None,
):

    service = DataCautionService()

    return service.evaluate(
        data_quality=data_quality,
        completeness=completeness,
    )
